"
" vim:foldmethod=marker

" Preamble - nocompatible {{{
" Use Vim settings, rather than Vi settings.
set nocompatible
" }}}

" Plugins (managed by vim plug) {{{
if has('nvim')
    call plug#begin('~/.local/share/nvim/plugged')
else
    call plug#begin('~/.vim/plugged')
endif

" A code-completion engine for Vim.
Plug 'Valloric/YouCompleteMe', { 'do': './install.py --clang-completer' }
" Generate .ycm_extra_conf.py for YouCompleteMe.
Plug 'rdnetto/YCM-Generator', { 'branch': 'stable'}
" Fuzzy search of files and open buffers.
Plug 'ctrlpvim/ctrlp.vim'
" Asynchronous Lint Engine.
Plug 'w0rp/ale'
" Drawer with functions/classes in a current file.
Plug 'majutsushi/tagbar'
" Git integration.
Plug 'tpope/vim-fugitive'
" EditorConfig plugin.
Plug 'editorconfig/editorconfig-vim'

" Transparently switch between tmux panes and vim split windows.
Plug 'christoomey/vim-tmux-navigator'

" Mappings for command mode in Emacs style.
Plug 'vim-utils/vim-husk'  

" Statusline.
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

" Snippets.
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'

" --- Editing
" Enter paired delimiters.
Plug 'Raimondi/delimitMate'
" Align text.
Plug 'godlygeek/tabular'
" Turn on CAPS LOCK.
Plug 'tpope/vim-capslock'
" Repeat.vim remaps . in a way that plugins can tap into it.
Plug 'tpope/vim-repeat'
" Change delimiters quickly: for example change 'word' to "word".
Plug 'tpope/vim-surround'
" Comment and uncomment quickly.
Plug 'tpope/vim-commentary'

" -- Color schemes.
Plug 'morhetz/gruvbox'                  " Retro groove color scheme.
Plug 'altercation/vim-colors-solarized' " Famous solarized color scheme.
Plug 'chriskempson/base16-vim'          " Popular base16 color schemes.
Plug 'rakr/vim-one'                     " Adaptation of the Atom color scheme.

" Interactive REPLs Over Neovim.
Plug 'kassio/neoterm'

" --- Plugins that improve support of different file types.
" Python.
" Fix python indentation.
Plug 'hynek/vim-python-pep8-indent'
" Improve syntax highlighting for Python code.
Plug 'vim-python/python-syntax'

" Markdown.
" Improved Markdown syntax.
Plug 'plasticboy/vim-markdown'
" Instant markdown preview.
function! _BuildComposer(info)
  if a:info.status != 'unchanged' || a:info.force
    if has('nvim')
      !cargo build --release
    else
      !cargo build --release --no-default-features --features json-rpc
    endif
  endif
endfunction
Plug 'euclio/vim-markdown-composer', { 'do': function('_BuildComposer') }

" Latex.
Plug 'lervag/vimtex'

" Tmux.
Plug 'tmux-plugins/vim-tmux' 

" Add plugins to &runtimepath.
call plug#end()
runtime macros/matchit.vim
" }}}

" Options for the editor itself {{{
" Enable file type detection and do language-dependent indenting.
filetype plugin indent on

" Enable syntax highlighting.
syntax enable

" Autoindent when starting new line, or using `o` or `O`.
set autoindent

" Backspace over autoindent, line breaks, start of insert.
set backspace=indent,eol,start

" Don't scan included files. The .tags file is more performant.
set complete-=i

" Use 'shiftwidth' when using `<Tab>` in front of a line.
" By default it's used only for shift commands (`<`, `>`).
set smarttab

" Default indentation settings.
set expandtab     " Replace \t characters with spaces.
set shiftwidth=4  " Number of space characters for indentation commands like >.
set tabstop=4     " Number of space characters used to visualize \t character.
set softtabstop=4 " Number of spaces that a <Tab> counts for while editing.

" Set `UTF-8` encoding.
set encoding=utf-8

" Allow for mappings including `Esc`, while preserving
" zero timeout after pressing it manually.
set ttimeout
set ttimeoutlen=100

" Hide backup and swap files by putting them in the `tmp` directory.
set backupdir=~/.vim/tmp//
set directory=~/.vim/tmp//

" Allow to switch between buffers even if the current buffer is modified.
set hidden

" Set project-specific settings by reading an .exrc in the current directory.
set exrc

" Disallow dangerous commands in an .exrc in the current directory.
set secure

" Show the possible matches just above the command line after pressing <TAB>.
set wildmenu

" Complete the next full match.
set wildmode=full

" Ignore patterns for filename completion.
" Archive patterns.
set wildignore+=*.zip,*.tar.gz,*.tar.bz2,*.tar.xz,*.rar
" Python patterns.
set wildignore+=*.pyc,*/__pycache__/*,*.so
" C/C++ patterns.
set wildignore+=*.o

" Stop showing annoying preview window during autocompletion.
set completeopt-=preview

set keymap=russian-jcukengost
set iminsert=0
set imsearch=0

" Check spelling.
set spell
set spelllang=en_us,ru

" Delete comment character when joining commented lines.
if v:version > 703 || v:version == 703 && has("patch541")
  set formatoptions+=j
endif

" Search upwards for `tags` file instead only locally.
if has('path_extra')
    setglobal tags-=./tags tags^=./tags;
endif

" Reload unchanged files automatically.
set autoread

" Map <Leader> key to <Space> key.
let mapleader = "\<Space>"

" Map <LocalLeader> key to backslash key.
let maplocalleader = "\\"

" Always move up and down by visual lines.
nnoremap k gk
nnoremap j gj

" Make `Y` to work from the cursor to the end of line, which is more logical
" (compare: C, D) but not Vi-compatible.
map Y y$

" Mapping for saving current buffer to file.
" Shortcut `fs` stands for "file, save".
nmap <Leader>fs :update<CR>

nnoremap <silent> [b :bprevious<CR>
nnoremap <silent> ]b :bnext<CR>
nnoremap <silent> [B :bfirst<CR>
nnoremap <silent> ]B :blast<CR>
" }}}

" Search options {{{
" Turn on incremental search.
set incsearch

" Highlight search matches.
set hlsearch

" Use mapping to clear the highlighting of `:set hlsearch`.
nnoremap <silent> <Leader>z :nohlsearch<CR>

" Use smart detection of case-sensitive or case-insensitive search.
set ignorecase
set smartcase
" }}}

" UI options {{{
" Set minimal number of screen lines to keep above and below the cursor.
set scrolloff=1

if has('mac')
    set background=dark
    colorscheme gruvbox
else
    if $COLORTERM == 'gnome-terminal'
        let g:solarized_termcolors=16
        set t_Co=16
    endif

    if $SSH_CONNECTION
        set background=dark
    else
        set background=dark
    endif
    colorscheme gruvbox
endif

" Font
if has("gui_macvim")
    set guifont=Menlo:h18
endif

if has("gui_gtk2")
    set guifont=Cousine\ 14
endif

" Highlight line under cursor.
set cursorline

" Make 80th column visible to help restrict line width.
set colorcolumn=80

" Show line numbers.
set number

" Show relative line numbers.
set relativenumber

" Always show window status line, even if there's only one window.
set laststatus=2

" Turn off showing current mode in command line.
set noshowmode

" Enable visual bell instead of beeping.
set visualbell

" Shortcut for rapidly toggle 'set list'
nmap <Leader>lws :set list!<CR>
" Custom symbols for invisible symbols such as tab and EOL
set listchars=tab:»\ ,eol:¬

" Show partial command in the last line of the screen.
set showcmd

" Lazy redrawing (helps with vim-tex performance issues).
set lazyredraw
" }}}

" Neovim-specific options {{{
if exists(":tnoremap")
    tnoremap <Esc> <C-\><C-n>

    tnoremap <A-h> <C-\><C-n><C-w>h
    tnoremap <A-j> <C-\><C-n><C-w>j
    tnoremap <A-k> <C-\><C-n><C-w>k
    tnoremap <A-l> <C-\><C-n><C-w>l
endif
autocmd BufEnter term://* :startinsert
" }}}

" Options for CtrlP {{{
let g:ctrlp_cmd = 'CtrlPCurWD'

" Configure `CtrlP` to use `ag` or `git` for listing files instead of using
" Vim's `globalpath()`.
let g:ctrlp_use_caching = 0
if executable('ag')
    set grepprg=ag\ --nogroup\ --nocolor

    let g:ctrlp_user_command = 'ag %s -l --nocolor --ignore _output -g ""'
else
  let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files . -co --exclude-standard', 'find %s -type f']
  let g:ctrlp_prompt_mappings = {
    \ 'AcceptSelection("e")': ['<space>', '<cr>', '<2-LeftMouse>'],
    \ }
endif
" }}}

" Options for Asynchronous Lint Engine {{{
" Remove pylint from the list of Python linters because it's very annoying.
let g:ale_linters = {
\   'python': ['pep8', 'pyflakes', 'flake8', 'isort', 'pycodestyle'],
\}
" Parse a compilation database (compile_commands.json file).
let g:ale_c_parse_compile_commands = 1
" }}}

" Options for Ultisnips {{{
let g:UltiSnipsExpandTrigger="<C-j>"
let g:UltiSnipsJumpForwardTrigger = "<C-j>"
let g:UltiSnipsJumpBackwardTrigger = "<C-S-j>"

" Options for python.
let g:ultisnips_python_quoting_style="single"
let g:ultisnips_python_triple_quoting_style="double"
let g:ultisnips_python_style="numpy"
" }}}

" Options for YouCompleteMe {{{
let g:ycm_autoclose_preview_window_after_insertion = 1
let g:ycm_python_binary_path = 'python'
let g:ycm_server_use_vim_stdout = 0
let g:ycm_server_keep_logfiles = 1
let g:ycm_confirm_extra_conf = 0
" }}}

" Options for vim-airline {{{
let g:airline_theme = 'gruvbox'
let g:airline#extensions#ale#enabled = 1
let g:airline#extensions#keymap#enabled = 0
let g:airline_left_sep=''
let g:airline_right_sep=''
let g:airline_powerline_fonts=1

" Customization of the symbols used by vim-airline.
if !exists('g:airline_symbols')
    let g:airline_symbols = {}
endif
let g:airline_symbols.spell = 'Ꞩ'

let g:airline_mode_map = {
  \ '__' : '-',
  \ 'n'  : 'N',
  \ 'i'  : 'I',
  \ 'R'  : 'R',
  \ 'c'  : 'C',
  \ 'v'  : 'V',
  \ 'V'  : 'SV',
  \ '' : '^V',
  \ 's'  : 'S',
  \ 'S'  : 'SS',
  \ '' : '^S',
  \ }
" }}}

" Options for vimtex {{{
let g:vimtex_fold_enabled = 0
let g:vimtex_view_method='mupdf'
" }}}

" Options for vim-markdown {{{
let g:vim_markdown_math=1
let g:vim_markdown_folding_disabled=1
" }}}

" Options for vim-tmux-navigator {{{
let g:tmux_navigator_no_mappings = 1

nnoremap <silent> <A-h> :TmuxNavigateLeft<cr>
nnoremap <silent> <A-j> :TmuxNavigateDown<cr>
nnoremap <silent> <A-k> :TmuxNavigateUp<cr>
nnoremap <silent> <A-l> :TmuxNavigateRight<cr>
nnoremap <silent> <A-\> :TmuxNavigatePrevious<cr>

" Write current buffer before navigating from vim to tmux pane.
let g:tmux_navigator_save_on_switch = 1
" }}}

" Options for python-syntax {{{
let g:python_highlight_class_vars = 1
" }}}

" Options for neoterm {{{
let g:neoterm_default_mod = ':rightbelow'
let g:neoterm_automap_keys = ',tt'

nnoremap <silent> <f10> :TREPLSendFile<cr>
nnoremap <silent> <f9> :TREPLSendLine<cr>
vnoremap <silent> <f9> :TREPLSendSelection<cr>
" }}}

